// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package users

type Role struct {
	ID   string
	Name string
}

type User struct {
	ID                            string
	Email                         string
	Phone                         string
	FirstName                     string
	LastName                      string
	DateOfBirth                   int64
	LicenceUrl                    string
	PassportUrl                   string
	InternationalDrivingPermitUrl string
	CreatedAt                     int64
}

type UserRole struct {
	UserID string
	RoleID string
}
