// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, email, phone, first_name, last_name, date_of_birth, licence_url, passport_url, international_driving_permit_url, created_at FROM users
WHERE id = ?1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, userid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, userid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.LicenceUrl,
		&i.PassportUrl,
		&i.InternationalDrivingPermitUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, phone, first_name, last_name, date_of_birth, licence_url, passport_url, international_driving_permit_url, created_at FROM users
LIMIT ?2
OFFSET ?1
`

type ListUsersParams struct {
	Offset int64
	Limit  int64
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Phone,
			&i.FirstName,
			&i.LastName,
			&i.DateOfBirth,
			&i.LicenceUrl,
			&i.PassportUrl,
			&i.InternationalDrivingPermitUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
